export const skills = {
  "language/framework": [
    "Java",
    "SQL",
    "Python",
    "JavaScript",
    "React",
    "HTML",
    "CSS",
    "Bootstrap",
    "Next.js",
    "Tailwind",
    "TypeScript",
  ],
  technology: [
    "Git",
    "Docker",
    "AWS",
    "Express",
    "Jenkins",
    "Jira",
    "Postman",
    "Stripe",
    "MCP",
  ],
  additional: ["Machine Learning", "PyTorch", "Hugging Face", "Web Scraping"],
};
export const experience = [
  {
    title: "Full-Stack Developer",
    company: "Litigation.gg",
    start_date: "May 2025",
    end_date: "Present",
    blurb:
      "Developed APIs and backend systems using NestJS and PostgreSQL, including a daily cron job to maintain CFR data and integrations with external data sources. Built MCP integrations to support context-aware chat interactions and improve user experience.",
    details: [
      "PostgreSQL",
      "NestJS",
      "API Integration",
      "Cron Jobs",
      "MCP SDK",
      "AI SDK",
      "Backend Development",
      "Testing",
      "Railway",
    ],
  },
  {
    title: "Backend Developer",
    company: "SPOEM",
    start_date: "Jan 2025",
    end_date: "Present",
    blurb:
      "Designed and deployed secure AWS-based backend systems integrating Azure APIs, automating secret management, and securing file downloads. Built analytics and email systems to improve user engagement and platform reliability.",
    details: [
      "AWS Lambda",
      "AWS API Gateway",
      "AWS Cognito",
      "AWS Secrets Manager",
      "Azure API",
      "AWS S3",
      "AWS SES",
      "AWS Amplify",
      "Next.js",
      "IP Analytics",
      "Backend Development",
    ],
  },
  {
    title: "Freelancer",
    company: "Self-employed",
    start_date: "May 2024",
    end_date: "Present",
    blurb:
      "Delivered full-stack solutions including an online learning platform for churches and a RAG model for querying HVAC documents, applying Next.js and AI technologies to real-world use cases.",
    details: [
      "Next.js",
      "SQL",
      "RAG",
      "AI",
      "PDF Parsing",
      "Full-Stack Development",
    ],
  },
  {
    title: "Full-Stack Software Engineer Intern",
    company: "Clutch Holdings",
    start_date: "May 2023",
    end_date: "Aug 2023",
    blurb:
      "Developed and optimized full-stack features across a Java/Scala/React stack, improving performance and data validation. Contributed to agile workflows with testing, Jira, and Jenkins for reliable deployments.",
    details: [
      "PostgreSQL",
      "Java",
      "Scala",
      "React",
      "JavaScript",
      "Jira",
      "Jenkins",
      "REST API",
      "Agile/Scrum",
      "Testing",
    ],
  },
];
export const certifications = [
  {
    name: "AWS Certified Developer - Associate",
    start_date: "Oct 2024",
    end_date: "Oct 2027",
    url: "https://www.credly.com/badges/5a53eb5b-541e-471b-8897-05ce81639165/public_url",
    description:
      "Able to develop, deploy, and debug cloud-based applications that follow AWS best practices.",
  },
];

export const education = [
  {
    school: "Rutgers, New Brunswick",
    major: "Computer Science",
    start_date: "Sep 2020",
    end_date: "May 2024",
    gpa: null,
    courses: [
      "Artificial Intelligence",
      "Information and Data Management",
      "Software Engineering",
      "Internet Technology",
      "Principles of Programming Languages",
      "Software Methodology",
      "Computer Algorithms",
      "Systems Programming",
      "Discrete Structures I & II",
      "Computer Architecture",
      "Data Structures",
      "Introduction to Computer Science",
    ],
  },
];
export const projects = [
  {
    name: "videogen.lol",
    github_url: null,
    site_url: "https://www.videogen.lol/",
    skills: ["Next.js", "Stripe", "AWS"],
    description:
      "Platform where users can generate 'reddit story' style videos with Stripe payment integration.",
    highlight: true,
  },  
  {
    name: "Portfolio",
    github_url: "https://github.com/markb2575/resume",
    site_url: "https://www.markbassily.com",
    skills: ["Next.js", "Tailwind"],
    description: "Personal portfolio website",
    highlight: true,
  },
  {
    name: "Text/Regex Search",
    github_url: "https://github.com/markb2575/regex-extension",
    site_url: null,
    skills: ["HTML", "JS", "CSS", "Browser Extension"],
    description: "Finds, highlights, and navigates text and regex matches on a page through browser extension.",
    highlight: false,
  },
  {
    name: "till-failure",
    github_url: "https://github.com/markb2575/till-failure",
    site_url: null,
    skills: ["Web Scraping", "React Native"],
    description: "A fitness tracking application",
    highlight: false,
  },
  {
    name: "RAG-Model",
    github_url: "https://github.com/markb2575/RAG-Model",
    site_url: null,
    skills: [
      "Hugging Face",
      "Sentence Transformer",
      "Marker",
      "NumPy",
      "Python",
    ],
    description: "A RAG model that retrieves data from PDFs",
    highlight: false,
  },
  {
    name: "Transformer-Model",
    github_url: "https://github.com/markb2575/Transformer-Model",
    site_url: null,
    skills: ["Python", "Jupyter Notebook"],
    description: "Implementation of a transformer model",
    highlight: false,
  },
  {
    name: "daily-blessings",
    github_url: "https://github.com/markb2575/daily-blessings",
    site_url: null,
    skills: [
      "Next.js",
      "TypeScript",
      "Tailwind",
      "BetterAuth",
      "Drizzle ORM",
      "MySQL",
    ],
    description: "Full-stack app for online daily blessings",
    highlight: false,
  },
  {
    name: "remove-osu-images",
    github_url: "https://github.com/markb2575/remove-osu-images",
    site_url: null,
    skills: ["Python"],
    description: "Tool to remove osu! game images",
    highlight: false,
  },
  {
    name: "LinkedIn-EasyApply-Automation",
    github_url: "https://github.com/markb2575/LinkedIn-EasyApply-Automation",
    site_url: null,
    skills: ["Python", "Selenium"],
    description: "Automates LinkedIn job applications",
    highlight: false,
  },
  {
    name: "CS440-Classification",
    github_url: "https://github.com/markb2575/CS440-Classification",
    site_url: null,
    skills: ["Python", "NumPy", "Machine Learning"],
    description: "Machine learning classification project",
    highlight: false,
  },
  {
    name: "Read-Coptic",
    github_url: "https://github.com/markb2575/Read-Coptic",
    site_url: null,
    skills: ["React"],
    description: "Coptic language learning tool",
    highlight: false,
  },
  {
    name: "CS440-FTR",
    github_url: "https://github.com/markb2575/CS440-FTR",
    site_url: null,
    skills: ["Java", "AI"],
    description: "Various A* search implementations simulating a 'fog of war'",
    highlight: false,
  },
  {
    name: "Jukeboxd",
    github_url: "https://github.com/markb2575/Jukeboxd",
    site_url: null,
    skills: ["MariaDB", "Express", "React", "CSV"],
    description: "Music playlist creation and sharing platform",
    highlight: false,
  },
  {
    name: "GapScanner",
    github_url: "https://github.com/markb2575/GapScanner",
    site_url: null,
    skills: ["Python", "Pandas", "Tkinter", "Threading"],
    description: "Stock market analysis tool",
    highlight: false,
  },
  {
    name: "StockScanner",
    github_url: "https://github.com/markb2575/StockScanner",
    site_url: null,
    skills: ["Python", "Pandas", "Tkinter", "Threading"],
    description: "Stock market analysis tool",
    highlight: false,
  },
  {
    name: "AI-Stock-Predictor",
    github_url: "https://github.com/markb2575/AI-Stock-Predictor",
    site_url: null,
    skills: ["LSTM", "Pandas", "Keras", "Tensorflow"],
    description: "AI-based stock price prediction",
    highlight: false,
  },
  {
    name: "translit-copt",
    github_url: "https://github.com/markb2575/translit-copt",
    site_url: null,
    skills: ["Python"],
    description: "Coptic transliteration tool",
    highlight: false,
  },
  {
    name: "OpenAI_DiscordBot",
    github_url: "https://github.com/markb2575/OpenAI_DiscordBot",
    site_url: null,
    skills: ["Python"],
    description: "Discord bot powered by OpenAI",
    highlight: false,
  },
];
